title: Gauzeder
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://ibanfr.github.io/gauzeder

aux_links:
  Gauzeder on Github: https://github.com/ibanfr/gauzeder

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true