title: Gauzeder
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://ibanfr.github.io/gauzeder

aux_links:
  Template Repository: https://github.com/ibanfr/gauzeder
